version: "3.7"

networks:
  ingres:

services:
  traefik:
    image: traefik:1.7
    command: --web --docker
    ports:
      # access this with the correct Host header to access the respective container
      - "80:80"
      # management UI
      - "8080:8080"
    volumes:
      # traefik does its magic by reading information about running containers from the docker socket
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ingres
    command: --api --docker
    labels:
      traefik.enable: "true"
      traefik.network: "ingres"
      traefik.frontend.rule: "Host:traefik.localhost"
      traefik.port: 8080

  rabbit:
    image: rabbitmq
    ports:
      - 15672:15672
    env_file: .env
    container_name: rabbit
    networks:
      - ingres
    labels:
      traefik.enable: "true"
      traefik.network: "ingres"
      traefik.frontend.rule: "Host:rabbit.localhost"
      traefik.port: 8080
